# Generated by Django 4.2.21 on 2025-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_business_card_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_card_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_review", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending_review",
                max_length=20,
                null=True,
            ),
        ),
    ]
