# Generated by Django 4.2.21 on 2025-05-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handyman', '0003_alter_handyman_bio_alter_handyman_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Handyman Availability',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='HandymanPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='handyman_portfolio/')),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='HandymanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='handymanpromotion',
            name='handyman',
        ),
        migrations.RemoveField(
            model_name='handymanpromotion',
            name='service',
        ),
        migrations.RemoveField(
            model_name='promotionnotification',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionnotification',
            name='recipient',
        ),
        migrations.AlterModelOptions(
            name='handyman',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Handymen'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='handyman',
            old_name='is_insured',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='handyman',
            old_name='is_licensed',
            new_name='verified',
        ),
        migrations.RenameField(
            model_name='handymanservice',
            old_name='flat_rate',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='detailed_services_description',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='offers_promotions',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='service_areas',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='services',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='user',
        ),
        migrations.RemoveField(
            model_name='handymanservice',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='handyman',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handymen', to='core.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handyman',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handymen', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handyman',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='handyman_profiles/'),
        ),
        migrations.AddField(
            model_name='handyman',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='handyman',
            name='specialties',
            field=models.ManyToManyField(related_name='handymen', to='core.category'),
        ),
        migrations.AddField(
            model_name='handyman',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handyman',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handymanservice',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='handyman.handyman'),
        ),
        migrations.AlterField(
            model_name='handymanservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handymen', to='handyman.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='HandymanJob',
        ),
        migrations.DeleteModel(
            name='HandymanPromotion',
        ),
        migrations.DeleteModel(
            name='PromotionNotification',
        ),
        migrations.AddField(
            model_name='handymanreview',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='handymanreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handyman_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handymanportfolio',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='handymanavailability',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='handyman.handyman'),
        ),
        migrations.AlterUniqueTogether(
            name='handymanreview',
            unique_together={('handyman', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='handymanavailability',
            unique_together={('handyman', 'day')},
        ),
    ]
