# Generated by Django 4.2.21 on 2025-05-30 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("handyman", "0004_handymanavailability_handymanportfolio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandymanJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.address"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handyman_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HandymanPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        choices=[
                            (3, "3%"),
                            (5, "5%"),
                            (10, "10%"),
                            (15, "15%"),
                            (20, "20%"),
                            (25, "25%"),
                            (30, "30%"),
                            (35, "35%"),
                            (40, "40%"),
                            (45, "45%"),
                            (50, "50%"),
                            (55, "55%"),
                            (60, "60%"),
                            (65, "65%"),
                            (70, "70%"),
                            (75, "75%"),
                            (80, "80%"),
                            (85, "85%"),
                            (90, "90%"),
                            (100, "100%"),
                        ]
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromotionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened", models.BooleanField(default=False)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="handyman.handymanpromotion",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handyman_promotion_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="handymanportfolio",
            name="handyman",
        ),
        migrations.AlterUniqueTogether(
            name="handymanreview",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="handymanreview",
            name="handyman",
        ),
        migrations.RemoveField(
            model_name="handymanreview",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="handyman",
            options={"verbose_name_plural": "Handymen"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.RenameField(
            model_name="handyman",
            old_name="featured",
            new_name="is_insured",
        ),
        migrations.RenameField(
            model_name="handyman",
            old_name="verified",
            new_name="is_licensed",
        ),
        migrations.RenameField(
            model_name="handymanservice",
            old_name="price",
            new_name="flat_rate",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="address",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="description",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="email",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="name",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="website",
        ),
        migrations.RemoveField(
            model_name="handyman",
            name="years_experience",
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.AddField(
            model_name="handyman",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="handyman",
            name="business_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="handyman",
            name="detailed_services_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of your services. Include specific keywords for better search results.",
            ),
        ),
        migrations.AddField(
            model_name="handyman",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="handyman",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="handyman",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="handyman",
            name="offers_promotions",
            field=models.BooleanField(
                default=False,
                help_text="Check if you want to offer promotional discounts",
            ),
        ),
        migrations.AddField(
            model_name="handyman",
            name="service_areas",
            field=models.ManyToManyField(
                blank=True, related_name="handymen", to="core.address"
            ),
        ),
        migrations.AddField(
            model_name="handyman",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="handymen",
                through="handyman.HandymanService",
                to="handyman.service",
            ),
        ),
        migrations.AddField(
            model_name="handyman",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handyman_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="handymanservice",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="handymanservice",
            name="handyman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handyman_services",
                to="handyman.handyman",
            ),
        ),
        migrations.AlterField(
            model_name="handymanservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handyman_services",
                to="handyman.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="HandymanAvailability",
        ),
        migrations.DeleteModel(
            name="HandymanPortfolio",
        ),
        migrations.DeleteModel(
            name="HandymanReview",
        ),
        migrations.AddField(
            model_name="handymanpromotion",
            name="handyman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="handyman.handyman",
            ),
        ),
        migrations.AddField(
            model_name="handymanpromotion",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="handyman.service",
            ),
        ),
        migrations.AddField(
            model_name="handymanjob",
            name="handyman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="handyman.handyman",
            ),
        ),
        migrations.AddField(
            model_name="handymanjob",
            name="promotion_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="handyman.handymanpromotion",
            ),
        ),
        migrations.AddField(
            model_name="handymanjob",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="handyman.service",
            ),
        ),
    ]
